apiVersion: v1
kind: Pod
metadata:
  name: toolbox2
spec:
  restartPolicy: OnFailure
  #  serviceAccountName: moova-sa
  containers:
    - name: toolbox2
      image: ezradibiase/moovatools:latest
      imagePullPolicy: Always
